### ISSUE TITLE
'press-kit'/brand guidelines page doesn't exist anymore

### ISSUE THREAD

**Issue by christophebedard** [ros-infrastructure/www.ros.org#32]
See: https://web.archive.org/web/20210420012034/https://www.ros.org/press-kit/

Just wondering if this is intentional. If so, was it moved elsewhere? The README here refers to it: https://github.com/ros-infrastructure/artwork.

The ROS logo files archive (downloadable using the "Download Press Kit" button) was useful, and I don't think all the files that were in that archive are on https://github.com/ros-infrastructure/artwork

**Comment by kscottz** [comment]
Media including press kit is available here: https://www.ros.org/blog/media/
