### ISSUE TITLE
Error [rospack] Error: package 'rosbag_storage' not found when using bag_reader.exe on Windows

### ISSUE THREAD

**Issue by ws17863276480** [ros-infrastructure/www.ros.org#51]
Hello everyone,

I have compiled a bag_reader.exe program using VS2019 on a Windows environment to read ROS bag files. While the program works perfectly fine in the ROS environment, I encounter the following error when running it on Windows:

> **[rospack] Error: package 'rosbag_storage' not found**

Here are my configurations and attempted solutions:

**Environment Variables:**
I have ensured that the ROS_PACKAGE_PATH environment variable is set correctly, pointing to the path containing the rosbag_storage package:

> **set ROS_PACKAGE_PATH=C:\opt\ros\noetic\x64\share**

**ROS Installation:**
I am using ROS on Windows and have followed the official installation guide to complete the setup.

**Package Installation:**
I have confirmed that the rosbag_storage package is installed. I tested it in a Linux environment, and it works fine there.

**Dependencies:**
I checked the dependencies of bag_reader.exe and ensured that all dependencies are installed and paths are correct.

**Compilation Configuration:**
While compiling bag_reader.exe, I have correctly added the libraries and include paths related to rosbag_storage in the CMakeLists.txt.

Despite these efforts, I still encounter the above error at runtime. I have also tried the following steps for further troubleshooting:

Manually checked if the rosbag_storage package exists in the path specified by ROS_PACKAGE_PATH.
Used the rospack find rosbag_storage command to confirm that the rosbag_storage package can be found.

**My questions are:**
Are there any other configurations or checks I need to perform?
Is there another way to resolve this package not found issue?
I would greatly appreciate any help or suggestions. Thank you very much!

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
